/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Word2Vec */

#ifndef _Included_Word2Vec
#define _Included_Word2Vec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Word2Vec
 * Method:    word2vecFromC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Word2Vec_word2vecFromC
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
